CropManagement/urls.py
from django.conf.urls import url
from .views import signup,Login,home,Logout,FarmsCreate,FarmList,\
                    FarmEdit,FarmDelete,FarmDetail,\
                    CropEdit,OtherFarmer,\
                    predictCrops,CropAutocomplete,LocationAutocomplete,AddSoilReport,predicCropsOnSoil,CreateReminder
app_name = 'CropManagement'
urlpatterns = [
    url(r'^$',home,name='home'),
    url(r'^register/$',signup,name='register'),
    url(r'^login/$',Login.as_view(),name='login'),
    url(r'^logout/$',Logout.as_view(),name='logout'),
    url(r'^addFarm/$',FarmsCreate.as_view(),name='add_farm'),
    url(r'^farmlists/$',FarmList,name='farm_list'),
    url(r'^farmedit/(?P<pk>[0-9a-f-]+)$',FarmEdit.as_view(),name='farm_edit'),
    url(r'^farmdelete/(?P<pk>[0-9a-f-]+)$',FarmDelete.as_view(),name='farm_delete'),
    url(r'^farmdetail/(?P<pk>[0-9a-f-]+$)',FarmDetail.as_view(),name='farm_detail'),
    url(r'^cropedit/(?P<pk>[0-9a-f-]+)$',CropEdit.as_view(),name='crop_edit'),
    url(r'^otherfarmers/(?P<pk>[0-9a-f-]+)$',OtherFarmer,name='other_farmer'),
    url(r'^predictcrops/(?P<pk>[0-9a-f-]+)$',predictCrops,name='predictcrops'),
    url(r'^cropsearch/$',CropAutocomplete.as_view(),name='crop_autocomplete'),
    url(r'^location/$',LocationAutocomplete.as_view(),name='location'),
    url(r'^soilreport/(?P<pk>[0-9a-f-]+)$',AddSoilReport.as_view(),name='soil_upload'),
    url(r'^predictsoil/(?P<pk>[0-9a-f-]+)$',predicCropsOnSoil,name='soil_predict'),
    url(r'^createreminder/(?P<pk>[0-9a-f-]+)$',CreateReminder.as_view(),name='create_reminder'),
    # url(r'^sendremainder/$',send_remainder),


]

Webtech/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('CropManagement.urls')),

]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

CropManagement/forms.py
from django import forms

from django.contrib.auth.forms import ReadOnlyPasswordHashField

from .models import MyUser,farm,SoilReport,MobileRemainder

from django.forms.utils import  ErrorList
class UserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = MyUser
        fields = ('email','first_name','last_name')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = MyUser
        fields = ('email','first_name','last_name', 'password', 'is_active', 'is_admin')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]



    # def clean(self):
    #     email = self.cleaned_data.get('email')
    #     password = self.cleaned_data.get('password')
    #
    #     user_exits = MyUser.objects.filter(email = email).first()
    #
    #     if not user_exits:
    #         raise forms.ValidationError("Invalid")
    #     else:
    #         if not user_exits.check_password(password):
    #             raise forms.ValidationError("Invalid")
    #     self.cleaned_data["user_obj"] = user_exits
    #     return super(UserLoginForm,self).clean()

class DivErrorList(ErrorList):
    def __str__(self):
        return self.as_divs()
    def as_divs(self):
        if not self: return ''
        return '<div class="errorlist">%s</div>'%''.join(['<div class="error">%s</div>'%e for e in self])

from dal import autocomplete
class AddFarm(forms.ModelForm):


    class Meta:
        model = farm
        fields = ('farm_name','farm_area','location','crop')


        widgets = {
            'location': autocomplete.ModelSelect2(url='CropManagement:location'),
            'crop' : autocomplete.ModelSelect2(url='CropManagement:crop_autocomplete'),

        }




class SoilForm(forms.ModelForm):

    class Meta:
        model = SoilReport
        fields=('soil_report','pH','EC','available_boron','available_copper',
                'available_iron','available_manganese','available_nitrogen',
                'available_phosphorus','available_potassium','available_zinc')



class ReminderForm(forms.ModelForm):
    # harvest_remind = forms.CharField(widget=CalenderWidget)
    class Meta:
        model= MobileRemainder
        fields = ('mobile_no','harvest_remind','water_remind','pesticide_remind')

CropManagement/views.py
from django.shortcuts import render
from .forms import UserCreationForm,AddFarm,SoilForm
from django.contrib.auth.views import LoginView,LogoutView
# Create your views here.
from django.shortcuts import HttpResponse,HttpResponseRedirect
from django.urls import reverse,reverse_lazy
from django.contrib.auth import authenticate,login,logout
from django.views.generic import CreateView,UpdateView,DetailView,DeleteView,ListView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .models import farm,MyUser,StateWeather,CropWeather,SoilReport
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.db import IntegrityError
#For messages
import json
from django.contrib import messages
#for model
from cities_light.models import City
import pyowm,datetime
from django.contrib.messages.views import SuccessMessageMixin

def home(request):
    if request.user.is_authenticated:
        return render(request,'CropManagement/home.html',{'my_template':'CropManagement/base.html'})

    else:
        return render(request, 'CropManagement/index.html',{'my_template':'CropManagement/index.html'})
def signup(request):
    is_register = False;
    form1 = UserCreationForm(request.POST or None)
    if form1.is_valid():
        form_final = form1.save(commit=True)
        is_register = True;
        print(form1.cleaned_data['password1'])
        user = authenticate(email=form1.cleaned_data['email'],
                            password=form1.cleaned_data['password1'],
                            )

        login(request, user)
        return HttpResponseRedirect(reverse('CropManagement:home'))
    else:
        return render(request, 'CropManagement/signup.html', {'form1':form1,'is_register':is_register})



class Login(LoginView):
    template_name = 'CropManagement/login.html'

class Logout(LogoutView):
    next_page = reverse_lazy('CropManagement:home')
    # form_class = < class 'django.contrib.auth.forms.AuthenticationForm'>


class FarmsCreate(LoginRequiredMixin,CreateView,SuccessMessageMixin):
    template_name = 'CropManagement/add_farm.html'
    form_class = AddFarm
    login_url = reverse_lazy('CropManagement:login')
    success_message = "Farm created Succesfully"
    def form_valid(self, form):
        """
        If the form is valid, save the associated model.
        """
        self.object = form.save(commit=False)
        self.object.user = MyUser.objects.get(email=self.request.user)
        try:
            self.object.save()
        except:
            return render(self.request,'CropManagement/add_farm.html',{'message':'already exist','form':form})

        return HttpResponseRedirect(self.get_success_url())

@login_required
def FarmList(request):
    farm_list = farm.objects.filter(user=request.user)
    return render(request,'CropManagement/farms.html',{'farm_list':farm_list})


class FarmEdit(SuccessMessageMixin,LoginRequiredMixin,UpdateView):
    model = farm
    form_class = AddFarm

    template_name = 'CropManagement/farm_edit.html'
    success_url = reverse_lazy('CropManagement:farm_list')
    success_message = "Form updated successfully"




class FarmDelete(SuccessMessageMixin,LoginRequiredMixin,DeleteView):
    model = farm
    success_url = reverse_lazy('CropManagement:farm_list')
    success_message = "Deleted Succesfully"

class FarmDetail(LoginRequiredMixin,DetailView):
    model = farm
    context_object_name = 'farm_detail'
    template_name = 'CropManagement/farm_details.html'
    temperature = 1
    date = datetime.datetime.today()
    status = "a"
    future_details_weather = []
    future_details_date = []
    future_details_status = []

    def get_weather(self,location):
        owm = pyowm.OWM('bd5e378503939ddaee76f12ad7a97608')
        print(location.name)
        observation = owm.weather_at_place(location.name)
        w = observation.get_weather()
        self.status = w.get_status()
        self.temperature = w.get_temperature(unit='celsius')['temp']

        self.future_details_weather = []
        self.future_details_date = []
        self.future_details_status = []
        fc = owm.daily_forecast(str(location.name))
        f = fc.get_forecast()
        for weather in f:
            self.future_details_weather.append(weather.get_temperature(unit='celsius')['day'])
            self.future_details_date.append(weather.get_reference_time(timeformat='date'))
            self.future_details_status.append(weather.get_status())




    # def getSoilReports(self):



    def get_context_data(self, *args, **kwargs):
        context = super(FarmDetail,self).get_context_data(**kwargs)
        self.get_weather(self.object.location)
        context['temperature'] = self.temperature
        context['status'] = self.status
        context['zipped'] = zip(self.future_details_date,self.future_details_weather,self.future_details_status)
        return context

class CropEdit(SuccessMessageMixin,LoginRequiredMixin,UpdateView):
    model = farm
    fields = ['crop']
    template_name = 'CropManagement/farm_edit.html'
    pk_url_kwarg = 'pk'
    success_message = "Form updated successfully"
    def get_success_url(self):
        return reverse_lazy('CropManagement:farm_detail',args=[self.kwargs['pk']])

@login_required
def OtherFarmer(request,pk):
    data = farm.objects.filter(~Q(user=request.user))
    farm_user = farm.objects.filter(id=pk,user=request.user).first()
    data=data.filter(location__region__exact=farm_user.location.region)
    data_crop_wheat = data.filter(crop__crop_name = 'Wheat').count()
    data_crop_rice = data.filter(crop__crop_name='Rice').count()
    data_crop_sunflower = data.filter(crop__crop_name = 'Sunflower').count()
    data_crop_soyabean = data.filter(crop__crop_name='Soyabean').count()
    data_crop_maize = data.filter(crop__crop_name='Maize').count()
    data_crop_jute = data.filter(crop__crop_name='Jute').count()
    return render(request,'CropManagement/other_farmer.html',{'other_farmer':data,'pk':pk,'data_crop_wheat':data_crop_wheat,
                                                              'data_crop_rice': data_crop_rice,'data_crop_sunflower':data_crop_sunflower,
                                                              'data_crop_soyabean': data_crop_soyabean,
                                                              'data_crop_maize': data_crop_maize,'data_crop_jute':data_crop_jute})

from django.db.models import  Q

def predictCrops(request,pk):
    location = farm.objects.filter(user=request.user,id=pk)[0].location
    print(location.region)

    try:
        state = StateWeather.objects.filter(state=location.region)[0]
        crop = CropWeather.objects.filter(Q(max_temperature__gte = state.avg_temperature)
                                      & Q(min_temperature__lte=state.avg_temperature)
                                      ).all()

    except:
        return HttpResponse("State data is not available <a href='/'>Go back</a>")

    return render(request,'CropManagement/predictCrop.html',{'crop':crop})





#
def predicCropsOnSoil(request,pk):
    try:
        soil_report = SoilReport.objects.first()
        for crop in Crop.objects.all():
            for nut in soil_report:
                if soil_report.organic_carbon < crop.organic_carbon-2:
                    organic_carbon = "Deficient"

                elif crop.organic_carbon - 2 <= soil_report.organic_carbon <= crop.organic_carbon+2:
                    organic_carbon = "Sufficient"

                else:
                    organic_carbon = "Excess"




        return render(request,'CropManagement/soil_predict.html',{})






    except:
        msg  = "First You need to upload soil report"

        return HttpResponse(msg)

from dal import autocomplete


from .models import Crop
class CropAutocomplete(autocomplete.Select2QuerySetView):
     def get_queryset(self):

         qs = Crop.objects.all()


         if self.q:
             qs = qs.filter(crop_name__istartswith=self.q)


         return qs


class LocationAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = City.objects.all()

        if self.q:
            qs = qs.filter(name__istartswith=self.q)

        return qs




class AddSoilReport(LoginRequiredMixin,CreateView,SuccessMessageMixin):
    template_name = 'CropManagement/soil_upload.html'
    form_class = SoilForm
    login_url = reverse_lazy('CropManagement:login')

    def get_success_url(self):
        return reverse_lazy('CropManagement:farm_detail',args=[self.kwargs['pk']])

    def form_valid(self, form):
        """
        If the form is valid, save the associated model.
        """
        self.object = form.save(commit=False)
        self.object.user = MyUser.objects.get(email=self.request.user)

        self.object.farm_name = farm.objects.get(id=self.kwargs['pk'])
        try:
            self.object.save()
        except:
            return render(self.request,'CropManagement/soil_upload.html',{'message':'already exist','form':form})

        return HttpResponseRedirect(self.get_success_url())

import requests
        
def getNews(request):
    news_data = requests.get("https://newsapi.org/v1/articles?source=the-times-of-india&sortBy=latest&apiKey=eb569205b123452cbd7d65832949c229")
    print(news_data)


from .models import MobileRemainder
from .forms import ReminderForm

class CreateReminder(LoginRequiredMixin,CreateView):
    form_class = ReminderForm
    template_name = 'CropManagement/remind.html'
    login_url = reverse_lazy('CropManagement:login')
    # success_message = "Farm created Succesfully"
    def get_success_url(self):
        return HttpResponseRedirect(reverse('CropManagement:farm_detail',args=[self.kwargs['pk']]))
    def form_valid(self, form):
        """
        If the form is valid, save the associated model.
        """
        self.object = form.save(commit=False)

CropManagement/templates/CropManagement/base.html
{% extends 'CropManagement/links.html' %}
{% block nav_block %}
<nav class="navbar navbar-toggleable-md navbar-inverse bg-success navbar-light fixed-top">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'CropManagement:home' %}">Dashboard</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
          {% block navigation_block %}{% endblock %}
          <span class="nav-item">
            <a class="nav-link btn btn-success" href="{% url 'CropManagement:logout' %}">Logout<span class="sr-only">(current)</span></a>
           </span>
      </div>
    </nav>
{% endblock %}
{% block body_block %}
{% endblock %}
</body>

CropManagement/templates/CropManagement/farm_confirm_delete.html
{% extends 'CropManagement/base.html' %}
{% block body_block %}
    <div class="container mt-5 ">
<h1 class="jumbotron bg-info text-white"> Are you sure you want to delete this Farm</h1>
<form method="post">
    {% csrf_token %}
    <div class="row m-4">
        <div class="col-6">
    <input class="btn btn-danger" style="margin-left: 80%;" type="submit" name="Delete">
</div>

</form>
        <div class="col-6">

        <a class="btn btn-danger" href="{% url 'CropManagement:farm_list' %}">Cancel</a>
</div>
    </div>
    </div>
{% endblock %}

CropManagement/templates/CropManagement/farm_details.html
{% extends 'CropManagement/base.html' %}
{% load static %}
{% block script_block %}
    <link href="{% static 'CropManagement/css/detail.css' %}" rel="stylesheet">
{% endblock %}
{% block navigation_block %}
   <ul class="navbar-nav mr-auto">
   <li class="navbar-item"><a href="{% url 'CropManagement:farm_list' %}" class="nav-link text-white">View Farms</a></li>
     <div class="dropdown">
  <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Crop Predict
  </button>
  <div class="dropdown-menu bg-success " aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item text-white" href="{% url 'CropManagement:predictcrops' pk=farm_detail.pk%}">Weather</a>
    <a class="dropdown-item text-white" href="{% url 'CropManagement:soil_predict' pk=farm_detail.pk%}">Soil Report</a>
    <a class="dropdown-item text-white"  href="{% url 'CropManagement:other_farmer' pk=farm_detail.pk%}">Other Farmer</a>
  </div>
</div>
   <li class="navbar-item"><a href="{% url 'CropManagement:create_reminder' pk=farm_detail.pk%}" class="nav-link text-white">Remainder</a></li>
   <li class="navbar-item"><a href="#" class="nav-link text-white">What's Happening Near by</a></li>
    </ul>
{% endblock %}
{% block body_block %}
    <section id="showcase" class="py-5" style="background-image: url({% static 'CropManagement/img/backsec1.jpg'%});">
    <div class="primary-overlay text-white">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 col-sm-12 text-center">
            <h1 class="display-4 mt-5 pt-5 mb-5">
                WELCOME TO YOUR {{ farm_detail.farm_name|upper }}
              </h1>
            <p class="lead">
                <i class="fa fa-map-marker" aria-hidden="true"></i> {{ farm_detail.location }}
            </p>
              <h3 class="display-5 mt-1 pt-1">
                  <i class="fa fa-thermometer-half" aria-hidden="true"></i>

                {{ temperature }}&degC
                  <i class="fa fa-tint pl-3" aria-hidden="true"></i>
                  {{ status }}
              </h3>
              <p class="lead"><i class="fa fa-leaf" aria-hidden="true"></i>{% if farm_detail.crop %}
    {{ farm_detail.crop }}
    <a href="{% url 'CropManagement:crop_edit' pk=farm_detail.id%}" class="btn btn-outline-secondary ml-2" >Edit</a>
    {% else %}
    <a href="{% url 'CropManagement:crop_edit' pk=farm_detail.id%}" class="btn btn-outline-secondary ml-2">Add</a>
{% endif %}
</p>
          </div>
        </div>
      </div>
    </div>

  </section>
<section id="weather-section" class="mt-5">
<h2 class="text-center mb-5">Weather for the next seven days</h2>
    <div class="container bg-inverse">
    <div class="row">
        {% for date,temp,statu in zipped %}
            {% if forloop.counter0 is not 0 %}
    <div class="col-2">
        <div class="card bg-inverse weather-card text-white p-0 m-0">
      <div class="card-block">
          <p class="card-title"><b>{{ date|date:"D" }}</b></p>
          <hr>
        <p class="card-text"><i class="fa fa-calendar mr-2" aria-hidden="true"></i>{{ date|date }}</p>
        <p class="card-text"> <i class="fa fa-thermometer-half mr-2" aria-hidden="true"></i>{{ temp }}&degC</p>
        <p class="card-text"><i class="fa fa-tint mr-2" aria-hidden="true"></i>{{ statu}}</p>
      </div>
    </div>
    </div>
            {% endif %}
{% endfor %}
    </div>
</div>






</section>
    <section id="soil-report">

<div class="container mt-5">
    <h3 class="text-center">Your Previous Soil report</h3>
    {% for report in farm_detail.that_farm.all %}

        <div class="card">
         <div class="card-block">
        <h3 class="card-title">{{ report.soil_report }}</h3>
        <p class="card-text">Uploaded on {{ report.uploaded_date }}</p>
        <a href="#" class="btn btn-primary">Edit</a>
             <a href="#" class="btn btn-primary">Delete</a>
      </div>
    </div>
    {% endfor %}
<center><a class="btn btn-primary m-5" href="{% url 'CropManagement:soil_upload' farm_detail.pk%}">Upload Soil Report</a></center>
    </div>
</section>
{% endblock %}

CropManagement/templates/CropManagement/farm_edit.html
{% extends 'CropManagement/base.html' %}
{% load bootstrap3 %}
{% block body_block %}
    <div class="container mt-5">
    <h1 class="jumbotron bg-info text-white">Edit your Farm Details</h1>
<form method="post">
    {% csrf_token %}
    {%   bootstrap_form form %}
    {{ form.media}}
    <div class="row">
    <div class="col-6">
    <input class="btn btn-warning" style="margin-left: 90%;" type="submit" value="Edit">
</div>
</form>
    <div class="col-6">

        <a class="btn btn-warning" href="{% url 'CropManagement:farm_list' %}">Cancel</a>
</div>
    </div>
    </div>
{% endblock %}

CropManagement/templates/CropManagement/farms.html
{% extends 'CropManagement/base.html' %}
{% block script_block %}
{% endblock %}
{% block body_block %}
    <div class="container">
{% if farm_list %}
{% for farm in farm_list %}
    <div class="card m-5 bg-info text-white ">
  <div class="card-header bg-inverse text-white">
      <div class="row">
          <div class="col-6">
    {{ farm.farm_name }}
              </div>
          <div class="col-6">
      <a class="btn btn-primary" style="margin-left: 60%;" href="{% url 'CropManagement:farm_detail' farm.id%}">View Details</a>
          </div>
  </div>
      </div>
  <div class="card-block text-white">
    <h4 class="card-title ">{{ farm.location }}</h4>
    <p class="card-text">{{ farm.crop }}</p>

<div class="row">
    <div class="col-6">
   <a class="btn btn-warning" style="margin-left: 90%;" href="{% url 'CropManagement:farm_edit' farm.id%}">Edit</a>
    </div>
    <div class="col-6">
        <a class="btn btn-warning" href="{% url 'CropManagement:farm_delete' farm.id%}">Delete</a>
    </div>
  </div>
  </div>
</div>


{% endfor %}
{% else %}
    <a href="{% url 'CropManagement:add_farm' %}">Add</a>
{% endif %}
    </div>
    </div>
{% endblock %}

CropManagement/templates/CropManagement/home.html
{% extends my_template %}
{% load static %}
{% block body_block %}
    <div class="container">
        {%   if user.is_authenticated %}


    <div class="row">
    <div class="col-12">
     <h1 class="mt-5 pb-5 pt-5 bg-info text-white text-center">Welcome {{ user.first_name |capfirst}} {{ user.last_name |capfirst}}</h1>
    </div>
    </div>
            <div class="row">
            <div class="col-6">
             <a class="btn btn-warning" style="margin-left: 80%;" href="{% url 'CropManagement:add_farm' %}">Add Farm</a>
                </div><div class="row">
                <div class="col-6">
                <a class="btn btn-warning" href="{% url 'CropManagement:farm_list' %}">View your farm</a>
                </div>
            </div>
            </div>

    </div>
{% else %}



{% endif %}
{% endblock %}
</div>

CropManagement/templates/CropManagement/links.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
   {% block title %} <title>Only Link</title>{% endblock %}
{% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<script
  src="https://code.jquery.com/jquery-3.2.1.js"
  integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
  crossorigin="anonymous"></script>
    <script
  src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"
  integrity="sha256-T0Vest3yCU7pafRw9r+settMBX6JkKN06dqBnpQ8d30="
  crossorigin="anonymous"></script>
 <script src="{% static 'material/js/jquery.js' %}"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <script>
</script>
    <script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">

{% block script_block %}
{% endblock %}
</head>
<body class="bg-">
{% block nav_block %}
{% endblock %}
{% block body_block %}
{% endblock %}
</body>
</html>

CropManagement/templates/CropManagement/login.html
{% extends 'CropManagement/links.html'%}
{% load bootstrap3 %}
{% block body_block %}
{% load static%}

       {% include 'material/includes/material_css.html' %}
       {% include 'material/includes/material_js.html' %}
{% block script_block %} <script src="{% static 'material/js/jquery.js' %}"></script>{% endblock %}
   {% load material_form %}
<div class="container">
<h1 class="jumbotron text-center bg-info text-white" >Login</h1>
    <form method="post" >
    {% csrf_token %}
    {% form form=form %}{% endform %}
        <div class="row">
            <div class="col-6 text-right">
            <input class="btn btn-primary" type="submit" value="Login">
            </div>
    </form>

<div class="col-6">
 <a class="btn btn-primary" href="{% url 'CropManagement:register' %}">Register</a>
</div>
        </div>

{% endblock %}

CropManagement/templates/CropManagement/signup.html
{% extends 'CropManagement/links.html'%}
  {% block body_block %}
      {% load bootstrap3 %}
      {% load static%}

       {% include 'material/includes/material_css.html' %}
       {% include 'material/includes/material_js.html' %}
{% block script_block %} <script src="{% static 'material/js/jquery.js' %}"></script>{% endblock %}
   {% load material_form %}
      <div class="container">

  <h1 class="jumbotron bg-info text-white   ">Register</h1>
  {% if is_register %}

      <p>You are Already Register</p>
      <a href="{% url 'ecommerce:login' %}">Login</a>
        {% else %}
      <form method="post">
          {% csrf_token %}
          {% form form=form1 %}{% endform %}
    <center><input class="btn btn-primary" type="submit" value="Register"></center>
  </form>
  {% endif %}
</div>
  {% endblock %}

CropManagement/templates/CropManagement/soil_predict.html
{% extends 'CropManagement/home.html' %}
{% block body_block %}


{% endblock %}